### ISSUE TITLE
AttributeError: 'Semantic3DSplit' object has no attribute 'sampler'

### ISSUE THREAD

**Issue by zcy1065670505** [isl-org/Open3D-ML#247]
Hi
I got a problem show in the title when I  want to train a model using semantic3d by follow:

- python scripts/run_pipeline.py torch -c ml3d/configs/randlanet_semantic3d.yml -m  --dataset.dataset_path  <semantic3d data path> --pipeline SemanticSegmentation

- Ubuntu18.04 
- CUDA-10.1 
- Pytorch1.6.0+torchvision0.7.0
- Python3.7.0

Cloud you tell me what' the problem? Thank you for you kind help!

**Comment by charithmu** [comment]
This was fixed in a latest pull request last time I checked. You need to add small code part to the dataset class. 
Basically "SomeDatasetSplit" class needs to inherit from "BaseDatasetSplit" class and call 
`super().__init__(dataset, split=split)  # sampler fix`
in it's __init__() method.

__init__() method of class BaseDatasetSplit(ABC) should be like below.
```
 def __init__(self, dataset, split='training'):
        self.cfg = dataset.cfg
        path_list = dataset.get_split_list(split)
        self.path_list = path_list
        self.split = split
        self.dataset = dataset

        if split in ['test']:
            sampler_cls = get_module('sampler', 'SemSegSpatiallyRegularSampler')
        else:
            sampler_cfg = self.cfg.get('sampler',
                                       {'name': 'SemSegRandomSampler'})
            sampler_cls = get_module('sampler', sampler_cfg['name'])
        self.sampler = sampler_cls(self)
```
I am copying this from my fork as I cannot find where was the fix. But there should be already a pull request from a developer which included these fixes.
