### ISSUE TITLE
Open3D-ML is not working under Windows(package was compiled without the Tensorflow flag)!!!

### ISSUE THREAD

**Issue by Nils-Treuheit** [isl-org/Open3D-ML#425]
### **Exception: Open3D was not built with TensorFlow support!** 

I tried to install open3d with the guide multiple times and always encountered that problem.
Sadly I also can not build open3d with all necessary compiler flags from source, because I am working in a virtual conda environment and there the cudatoolkit seems to be incomplete(nvcc can not be found) :/
can you please help me?

It seems like there are a lot of install issues regarding these above mentioned exception - Could you please fix the issues with the package you provide via pip otherwise I would strongly recommend to delete Windows from the supported platforms.

**Comment by sanskar107** [comment]
Hi @Nils-Treuheit 
We disabled building the tensorflow ops on Windows because we ran into some issues, e.g. tensorflow 2.0 did not ship with the required libs and headers for building ops. We did not look into this again with a more recent verison of tensorflow. If you want to give it a try, you can simply remove remove this line
https://github.com/intel-isl/Open3D/blob/master/cpp/open3d/ml/CMakeLists.txt#L2

Anyway, Windows WSL can be considered as a workaround at the moment.

**Comment by ma7555** [comment]
@Nils-Treuheit did you try?
